services:
  postgres:
    image: "postgres"
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - ./migration/docker-database-initial.sql:/docker-entrypoint-initdb.d/docker-database-initial.sql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 5s
      retries: 5
      start_period: 10s
      timeout: 5s

  pgadmin-compose:
    image: dpage/pgadmin4
    env_file:
      - ./.env
    ports:
      - "54321:80"
    depends_on:
      - postgres

  myapp:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - ./.env
    environment:
      - POSTGRES_HOST=postgres
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      postgres:
        condition: service_healthy
